apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6Xa3lA31GUZ1lar4IE9CsYjmekl1QIA=,iv:ZwdEMIFG1FtpMvl8KBz8FpFvYwHee2nSz0yxmTMxwPc=,tag:W+6bRb8XNvqBlTD8tTklIg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:wTU294v9p3p1EP0SB9NXur0Raci/LwJDAGEFIskXj8JLoAqw4g==,iv:NVG7BP1S/3a460sZPySOKP0QiZOCRZFS8+c+97MIVmc=,tag:kc2pX21rtRU/QHn1c/322Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:6j1f07ccVGre7Q2fHbDfbviR9ts=,iv:gH3rj2ogiWHDOBQo/bmOumuAMknGL/DV9TzAdtbINQw=,tag:kBCsj7opyzeluUCuRu03+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g3tlvcegfpl0nnaufvw57f9q5hl4h5zyuwrvwnwuahe9dauej3rsf0rf9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T1l2cStlZ2dHSm12ZkQ1
            cXU3ZU92Q1N4LzJkR252TGdpSkRGeC9SVVNzCmp1TUhLZC92UzZJY3pQWlZiZWds
            QzVOZ05CcmxlMG9Mc0lGbkZqaGFxUTgKLS0tIEhCSHFxcFQ2UDRGem1paUNLSUV0
            ak83TmRDKzROdlU0MTZ0bS9tZFE4VUUKFzckYH8+1jdBlsi+Z4RwLlMzw/++sRQr
            OoLLG78CJXVK31dprhDRGclKti0pP6MIEgcCYqL4pE+/C/WqYsJNsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-22T19:46:08Z"
    mac: ENC[AES256_GCM,data:0xEu+yyYa458AYo/BxsTEZnRu/vIDdU/t4SnO4MyTGx0kzYXsrQkbPfIaS9GgvIcSXjrsIayYYOwl+omuPq4I75kGpOsyVg22yl2YvYkh1xri0TKQo7okgBk4tJTniqutRl8L6grZqUio32Ktf6LkYo+Sk6LWqjF3wsH/NScGJI=,iv:nczZTUUHT40dVQs+7ReIY9rZsoo1vsyqjC7f03ow5s4=,tag:ZzdOXh9bKfd8fqDIoFhPkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
