---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cf-tunnel
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: cloudflare/cloudflared
      tag: latest
    args:
      - tunnel
      - --no-autoupdate
      - --metrics
      - 0.0.0.0:8081
      - run
      - --token
      - $(token)
    envFrom:
      - secretRef:
          name: cf-tunnel
    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 74M
    service:
      main:
        enabled: false
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8081
            scheme: HTTP
      readiness:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8081
            scheme: HTTP
      startup:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 30
          httpGet:
            path: /ready
            port: 8081
            scheme: HTTP
