apiVersion: v1
data:
    token: ENC[AES256_GCM,data:fkK5KM8dTaIbgAGK9GtUQTc+3PWjYyAB1g6oDG5Ls0O1xwNbeIS6pSVdgoyaxb6vTNGMcLpERMWL1UTZHmwuyWoBNFNyotBh6Se/5T/j5ZFvmz+aqAw9vIi4iUELRh5PQxG+f805nxMmFZrZmYCRTNzkk3cmPdoDkgYXblohZEB/hH62EJG3QTFMpADp3jla3P6D9b900Ehe0lgFEUeIg1KRDGivOt7+WnCu02NjFQScpRleQZnjA+yQqKMvg5I7GGhjrzuq6eEHlFMFfQkIaWrp44tM+8frcX3eKJAuuij5T+nrsBrvDJ0kx9huIk5IzoSpgmdoYAU=,iv:UbNyrWMpTGXYZzoiOuwaeHKaPCuLEWzMzkHz3vRyHtE=,tag:ztcLGcbvfdUyUUz/7z8AUQ==,type:str]
kind: Secret
metadata:
    name: cf-tunnel
    namespace: networking
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g3tlvcegfpl0nnaufvw57f9q5hl4h5zyuwrvwnwuahe9dauej3rsf0rf9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ05EdmZZdnJRL0JoUTV5
            SGg0cHNxUUs3ckcxamgzVnY1dGk1SVh3V3hnCkhvaVlHM3dxQXlRWlI0b2JiNXFj
            N3p0aHZmbUkwTys1SUVBNkFndm9FVjAKLS0tIFFmNTF4QnM2VHlVcXdPNmxpUEZL
            UURxTXJHbER1Rk52NjJPQzR6RXFOdlUKRCQe2Xl7ei5ZKt1VuvLTTdXTA4cUSRpT
            SXSDhHjXEw9FSBGfUaeStY9NCed4wixJ3Di3KX++wTJClmzKjfvcjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-22T19:46:08Z"
    mac: ENC[AES256_GCM,data:71BfxYdq1FaYSI9klOIWZRqPeZNRby8QCZ2v6kwyusWSIoQLbFrzuMRqIk+KuemsWWK/TbY4oD6r+upLOhyJvfE/sUskYwwjQ8FkMiAlqlDQV2KgmruHXGhKm8agKnO/nYxsww0QWSv2yiMO9VOVzXtN5iTB7iqrfPhKsQhRhHo=,iv:AHCyW33VXFcqanB+4UC2DgdX+nI3d+43snMv4mzanrY=,tag:1c96cNSgOR6blfcV3i+09w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
