---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1kqeycwnqdu05muczrt8kmtsrgrdf04unaxpzeryp0lg9tg49ya9q3tjm6y"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1kqeycwnqdu05muczrt8kmtsrgrdf04unaxpzeryp0lg9tg49ya9q3tjm6y"
