# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:B+mmCt0=,iv:ShNEGmB3W/N0RPEVxKm97tetlo6mXIjxcimqIXKiL+E=,tag:vLcSd8QGe3XXAMc15E53eg==,type:str]
    admin-password: ENC[AES256_GCM,data:G6WfU68gBqkf,iv:GWJU1peCevvxAb9/yozcOfmqYS7pBaw+RcORUkHDSBc=,tag:TDp6zBExmUVMw2uje2QN/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g3tlvcegfpl0nnaufvw57f9q5hl4h5zyuwrvwnwuahe9dauej3rsf0rf9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeG83bDJZcDI1RERublIr
            ZkRaTkI4MktyUlBvTEl2dWdQQjM5elBpWWtZClZRRzJOUWdhQTdEWVhGaTBqaEFR
            ekNLZm9PbGhld1dPMEdiMlJsVVJ3bnMKLS0tIFBWb3A2RTY5WnBBcjBNeVFTQ1Rk
            MHRtMWU3dG40K1htbWwya2RSdDh2cWsKlfVR3b4fXl3qZoJ64d6YTokYfeKptV7U
            tCqcdYxsqSxj0yLXcrXzNFdMVxLGgYoZyYzx9dhqh2TCed/OlaFP5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-22T19:46:08Z"
    mac: ENC[AES256_GCM,data:f5GisFyPHEmbKV3OxvJNuC5iZw8MOL0uqcEhYXzezRemfNl/tbNLb+JVigYqgLRznCGhCiKyQcIm3ViY+h5RDhmved4xpikU4VFrGsN1RCf5VJbvymTjNXNSd0SigA2C3tkr6HvS6oxcYl/Gq3bTeEHS8ktEjf5Tx7DZXLS+9vk=,iv:Pp2YtYnxPx104/aF8gNMsMuaDK5VI6KVRskkR5MgT0s=,tag:IkjiMGCinWtyBRa05MeEYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
