apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:5lbCTMIy2TXSzcdI3SerNvI/+LMcL6pRJZjtKw0AQRS+2q9Eyg==,iv:pC0rZAUwDYNlf6sLBIcK0q2WCzb/wIxrIZ7qEqXdyhc=,tag:slLcujk275AVDVCTUujgKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g3tlvcegfpl0nnaufvw57f9q5hl4h5zyuwrvwnwuahe9dauej3rsf0rf9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydWRoMWZtYVhOaTZLL05F
            S1lKdjFUaSt5SG95TytpYTgxWUoxTyt0bGlzCmUyeGRLMG5XSmJCSHhmUU9Ub3Z3
            RElDeTdmLzJsdUpPYmdoYUJOV1dzT2MKLS0tIGFHdkRHZnJqRVM4L2dyRnQ1ekhF
            S3pwK3YxWnRTOEVjdXVmeVoxazM1TnMK/89fjOBAi4gV4kLF1GFkib3Mj527seVF
            cfhj6sB12NTxuKI06nbKXEhl1LcgITcUZX8dlIe76CTO9zxjx7kVdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-22T19:46:08Z"
    mac: ENC[AES256_GCM,data:oUzxJqWNDV8QMq29XrMLt+ASnnq20lZOP9NppwQF+OOho5KXgD3AaeDVC1Mkxvs6Kcio/EuIWK3Y4Qo0XXgJM4ltoGwvSfgoJHGWt7QpWjbDDC02m4bgjSPem/9foGSe93LpthleR9+PpDPNSPEa0luABYp3uyW5luVeg4qQ2TA=,iv:4+OCcTX0/td+tMD0/jLPiBivBppsmNf38uaGjEfJzhs=,tag:KlgGWNYV2mhGGJ4Inr66gA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
