apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:rw10g4zSOFiwbJf9TmC5GorChCgSwu4=,iv:YhLmWwP5tz0Z3PIqeCFydwjxS9bDUtFivpt03tNp7TY=,tag:qfgt3nMBPtvCgv39vEWtKA==,type:str]
    api-key: ENC[AES256_GCM,data:EtWk1P+TkDcQzMDjpI7P0SNOJQwk3Gs0/TUR1orgQYc2lvKmnw==,iv:gaWP5qm46FxU1BaUfef79lHgc3ognG+lxPH6i5+Ns5Y=,tag:iitmIPYi45St5H7fW27yAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g3tlvcegfpl0nnaufvw57f9q5hl4h5zyuwrvwnwuahe9dauej3rsf0rf9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMGk2Q3c2d2YrV2U4b2tJ
            MjZOS3VubGZZUGZzaUtib1pCeTNrNWNBL0NrCnQ1Y29qVGZDMEIxVmJ0QUJiNHBn
            RUpVcTNqVi9OZkoyWURCUm02VkxGc1EKLS0tIGh1S2kxenViRGU0REN0RW95cUhR
            cmkvTkVLc3JxUjBERDFOa2lYS1NpZEEKWclm2m00evcd39GJKQtjYnTfvcmRDG0V
            /OoMDtPmd1JnefyyjWKtb6tmRVHYQV35sMwNJnAoNHgmu5gG97XXIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-22T19:46:08Z"
    mac: ENC[AES256_GCM,data:7k3zfhy90BuTrtdQOGd36opAjSyhCx+QxEZd41yBMkCwMecrNvKfElboVnKhFhBsIMVbUPB17ROM9mWWsIw2I8PEZCgj8z8umf9MYrzXfCf3MHkl29deKsfXbTR3efYYuch3wV+BlRIDyf8FnG2/+sJtFXmWN7BGWXtUpVzLwtI=,iv:vA83+Kap1sgF7uIyF/rdfxgw0uFQhkZFtHOsxoLo04Y=,tag:6VQmECgDWMXibJBMbbbfrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
