---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vector
      version: 0.21.1
      sourceRef:
        kind: HelmRepository
        name: vector-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    role: "Stateless-Aggregator"
    podMonitor:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: ${METALLB_VECTOR_ADDR}
      externalTrafficPolicy: Local
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
      sources:
        kubernetes_logs:
          address: 0.0.0.0:6000
          type: vector
          version: "2"
        talos_kernel_logs:
          address: 0.0.0.0:6001
          type: socket
          mode: udp
          max_length: 102400
          decoding:
            codec: json
          host_key: __host
        talos_service_logs:
          address: 0.0.0.0:6002
          type: socket
          mode: udp
          max_length: 102400
          decoding:
            codec: json
          host_key: __host
      transforms:
        kubernetes_remap:
          type: remap
          inputs:
            - kubernetes_logs
          source: |-
            .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"
        kernel_hostname_transform:
          type: remap
          inputs:
            - talos_kernel_logs
          source: |-
            r1 = replace!(.__host, "192.168.1.51", "elite1")
            r2 = replace(r1, "192.168.1.52", "elite2")
            r3 = replace(r2, "192.168.1.53", "elite3")
            r4 = replace(r3, "192.168.1.54", "elite4")
            r5 = replace(r4, "192.168.1.55", "elite5")
            r6 = replace(r5, "192.168.1.56", "elite6")
            r7 = replace(r6, "192.168.1.41", "elitepi1")
            .node = r7
        service_hostname_transform:
          type: remap
          inputs:
            - talos_service_logs
          source: |-
            r1 = replace!(.__host, "192.168.1.51", "elite1")
            r2 = replace(r1, "192.168.1.52", "elite2")
            r3 = replace(r2, "192.168.1.53", "elite3")
            r4 = replace(r3, "192.168.1.54", "elite4")
            r5 = replace(r4, "192.168.1.55", "elite5")
            r6 = replace(r5, "192.168.1.56", "elite6")
            r7 = replace(r6, "192.168.1.41", "elitepi1")
            r8 = replace(r7, r'10.*', "talos")
            .node = r8
      sinks:
        loki_kubernetes:
          type: loki
          inputs:
            - kubernetes_remap
          endpoint: http://loki-gateway.monitoring.svc.cluster.local:80
          encoding:
            codec: json
          batch:
            max_bytes: 524288
          out_of_order_action: rewrite_timestamp
          remove_label_fields: true
          remove_timestamp: true
          labels:
            app: >-
              {{`{{ custom_app_name }}`}}
            container: >-
              {{`{{ kubernetes.container_name }}`}}
            namespace: >-
              {{`{{ kubernetes.pod_namespace }}`}}
            node: >-
              {{`{{ kubernetes.pod_node_name }}`}}
        talos_kernel:
          type: loki
          inputs:
            - kernel_hostname_transform
          endpoint: http://loki-gateway.monitoring.svc.cluster.local:80
          encoding:
            codec: json
            except_fields:
              - __host
          batch:
            max_bytes: 524288
          out_of_order_action: rewrite_timestamp
          labels:
            node: >-
              {{`{{ node }}`}}
            facility: >-
              {{`{{ facility }}`}}
            namespace: "talos:kernel"
        talos_service:
          type: loki
          inputs:
            - service_hostname_transform
          endpoint: http://loki-gateway.monitoring.svc.cluster.local:80
          encoding:
            codec: json
            except_fields:
              - __host
          batch:
            max_bytes: 524288
          out_of_order_action: rewrite_timestamp
          labels:
            node: >-
              {{`{{ node }}`}}
            talos_service: >-
              {{`{{ "talos-service" }}`}}
            namespace: "talos:service"
