# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    BUCKET: ENC[AES256_GCM,data:KS1G7S9R,iv:z0/iAOG5pelG9VPWulyrUmx4ABBJH3yGsEGllAGf7Q4=,tag:I0lzzXEnrr6VEAVLEVHmqw==,type:str]
    ENDPOINT: ENC[AES256_GCM,data:nvvGEI1IshWymVLqlskYZg==,iv:GV6V9n8242Mg1ORkY4Y8ytNtsqHmK9rt86ZD8IfQAAg=,tag:eM0kzXXyY0CO2giDX3bhUg==,type:str]
    REGION: ""
    ACCESS_KEY: ENC[AES256_GCM,data:wHgYH/C+AGcyEJERXyscJA==,iv:QN8umtEH2F7x23PAS/FdAD/rI9XLGyEYMvLyn7v9KTI=,tag:KBYA/8R2JXQi5LK/lf3jzg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:0UVZkS9B7T80QJoD/u/CLytXBkOJpHlWM2AxyeZKrc0=,iv:/vEI0NOnZl9KPFb8BY9IxjLokETZ5Pq/16TZ26fjNJ8=,tag:eErttTgMgPqJ7fgGRgJY4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g3tlvcegfpl0nnaufvw57f9q5hl4h5zyuwrvwnwuahe9dauej3rsf0rf9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZnFYYmsrVGhKM3ZvRDFP
            Nm1DN3RyZUZRdnk2VVEycVlWaFhUeVcyZERzCkduaGRHQTlqVXFWbGVnZkQ1WUlo
            VVZvMW1XV3RBQ3NJaXdXM2ZXUEZLN2MKLS0tIHU2K1MrM3FLbXJJN0I0aG9lOWh0
            ZnI3RkF4c0V2dk5zSUNURXdoZVlLdlUK4CK4ggARVMGzN+1suZ5oXzouGvuTH2bt
            Lc+w0l2+VG7DDazF4p+m5z1GlQmms1BDREVdu5u3nFQq+NGE0Cq+qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-22T19:46:08Z"
    mac: ENC[AES256_GCM,data:F8Buin8dRUK5CtNhtbhw8FZh/rrhC2F0m750bDIm1i94ad82Mah7e6l2BkObak7CwXMDdrUlHQFG7rofjmO2d9fD/fjpcmcNvkSc4HWw9nixCZNZaqWjy3xiiu8YEpb4X/citVt9Oa0TRNSbVD0AcaLOsuNBUWkoujefOxBcYAo=,iv:OGTUvtSeLmsIOEF0b6riH6H9EHk6oWM2cpWMyKjE3l4=,tag:je6C6Ezgy92zSuxj+ebLIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
