apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:lq8Hx54NRlguq3wGJTGJ5EgeYDzcoXKkRPA3lTR9ziUpT1NxdXiXS6Nv4bEjl1VqzmxqMbhRNGNRbiel1SllfShcJdxamA3Bpag0KUsnedIfuXjxqNUx+FggnQBdbw==,iv:0YjMYH+jZ8220t527iMgEH2L3jKuVYMjdXGPkhN5aGE=,tag:AM4KnGcYsx2k0Cf4Ovi6Vw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:aPHIjmMLHwmY9WnG4dL1,iv:VJoNB5TiqIWbLkIwIhBtZGnX12bDeoSdT35DRO3rn7s=,tag:JssaHLrY+qZk3tRshvVVIA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sX9kGhNHij+Gv1JohS1meTtGh0c1nM4=,iv:bw1XHNwjkq3rsBrvDyl/fLUpTyP1BXbHuoYscLeX0Z8=,tag:zspfSF6kaj7rdUwBiRE6Vg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4yfhHAX4r0d3YQf6TB5Pmeqi1jCC/L7iJ4DAArhUfIjbwqUM,iv:T32kJHIta2GhdDSclO/cGOrIJ+W+OjVPVOjkUYr/WLY=,tag:pGwSouzqGCsNEXTFjgx5Ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kqeycwnqdu05muczrt8kmtsrgrdf04unaxpzeryp0lg9tg49ya9q3tjm6y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSzdoR0p0Ui80cU5LdTVE
            YnA2bWhTeWpvcmovVUdUMUNxMjZHTHNPSUNJCkRmM3p4Z1JEL3BjcDc4akhLY2p3
            NUdIaERrWnZoS0ZyZ1dnZDR5TVRveTAKLS0tIGkwdDhpcXZ0UDVITzlkQzZ3QjFY
            U0hhcGxxWHhLUC9DQmdPRFRsV1lERjAKeqVY5z8Ki1BAhUEz3AMK5lRAo74QDJwT
            WbvVCI28NsT++83LrtevpEvpCqxiZpRxEFNXeqvJUGFe2UbCpmVLNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-25T13:19:32Z"
    mac: ENC[AES256_GCM,data:GrbR3ACEybhCT4GAxg2Pl3kWMtPrlJqzKF/9tEx3uzZzspBsQLX1GMQCLLIoDAY52Hk2eVlQ+lSAdE2MajvMGLiff+3RCQDZeMm/9s4WynCIMaD4sCKOxc1ncN3QkC/xQIEKO+26Sz4r+ewywJen0p89U0iHjPX+qDf60ihVWls=,iv:zpWaMSjVSm1kS8cI5UhOTIABnw5ZBEkIQNMRAkg9fos=,tag:qqMJTKB5INzPOrj2D6hWYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
