apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ofqVshl3VmtIw5LK1ZpJ,iv:zw88ZVQ3FESVUYAxgUwiSsVCq5IX9V0nQDpr8zIJPB8=,tag:CXm5fWc+tOYte4FVUZx0Jw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:R9cLdM2QjdrmO7qV3UzRuJaS6Hg+U6Y=,iv:aB0zNih1GPwZXhxEv1lO9UhqTqyddMKGGp0hBrGTqAY=,tag:M27+QDqjREcIZvM69i5qGw==,type:str]
    SECRET_ALERT_EMAIL: ENC[AES256_GCM,data:cDMGbj9ws2C1gtal/hp4Ceee4G9tKmc=,iv:KPbm8SpGnjl7KxM9mz0hUvgzPbcsozvqyft+gWnvTq4=,tag:n+KvD9vBzQKfMa+itI9/mw==,type:str]
    SECRET_ALERT_SMARTHOST: ENC[AES256_GCM,data:pRp2/I+2lQcLNh87Wxqz94xNDHnp,iv:a941KTJlqoNoGcTLusdobBEuHf2S9qq7HDVnWiOP5Ss=,tag:ziV/xvO8bZIIMFauHa0IdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g3tlvcegfpl0nnaufvw57f9q5hl4h5zyuwrvwnwuahe9dauej3rsf0rf9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z1BnbitHUHRYb2E5TnAx
            SVhXTVVKNm1ibVVhNjlZSVMrQjl3aVpQZWd3CjBWZlNwQ3JoR3pmaVpwVjdYMklU
            UGIzVERLSmlKMGdRMFZEd3RocG9TVkEKLS0tIGR6MlpaQjl0MEMxZ084U2Z0SHFj
            Z3dvWnBBMkNyNUw0ZGc0OGhLYzZrSGcKkzIM+kRVSr/7WIwd+LRjkNRM5KKc+t2U
            Y8fExwbsH5GBW+8SJctnrZCn8qW16VzJnjAfxsDfC1TDntLSAXYxSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-23T22:24:20Z"
    mac: ENC[AES256_GCM,data:ZdRtb0itfxtRHqjk3mriL8njkZQTbVaVL47AP7y+EKdFwdbHGEGG3L0/Il+Ze0BapZZWYepdDzP2yjqsfiK7hrKbwedKe55lsU8Vs5aL/khJSP9zmUxX2QJaezAHqP1BzW8qr6dcbwgWBJ0hoTEKEI0gt7i/PNYIgVyxHvW2vvU=,iv:VNfHI+lHPVCnIZWt3iUdF6cgGTbT1QDBClaCjsI24QY=,tag:bN7dhPw2LytaGDPpwuzZww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-key
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:aNasjWsSkFuMBLrIKeQ/ZDXIQ2/JGVVFlwwCZFk93g==,iv:ApsFNTTtTqX8Wx8KwJdqmMPGQMbY2fC3QowVtJOM5F0=,tag:yfcTmekY2i+bwg8mlgkoug==,type:comment]
    identity: ENC[AES256_GCM,data:CUZM+puwOBT1d/L3uOMvb/RqWOleZb6fSQSzFVd61Af69fojRXPsT1kDMy1DzQpK/fgnhipgZ4nStqFgvl6Fa5ni+RKYVUFu24FIdaoDsu4RaHexJqVm5KL0RnW1XULE+VZ4PHlB37fGw07RKrPj5MuoJZkOQPOMakAhthdBTvPKhUp9AQ/9cyLxohE0VK//xVCquMhgyA2WQo7mUSwarvcReEVA3TkzLo0dRKoW4KAD4JjqBisNTtIQOVpRkZvPFllK7M4D/9EodAWium6i0TvrLSUG2GVq9HpcA6DNNgDkOFKapRCcI0xjbHEB9R/5MmiIbdB0ajI3ZeyF/RBp04HWlMXI//uIecgsynepXeCsPuTAx1tAfmsM80eo5Yi/0S1SethrETnlWsqzhdvA3dCVtUZhnU/CQzLYOyt1J+XAnWfp1PZ5lqFJDsWAUEcMQGt9RLKRLHAxaYm9phqvLJZpsuzmi04OGvqRrLQOKgiAWg4ypzCLbD1+ZzJ5SuNJGIrIMtngM1Kfgw/TS5ZlwtymsLnxy8ImbjvlXgd6GRirYpT9WRyvLE1TA7nHgf7OZh5ORvJ/HpWdAlJZo4rNFoLog4h06kK/GHzqLhwmi0k0w+xb1yBqCZAbkzv+6g0mgsNJOBgqEmIjAg2+C11xBY1zYWA7/j2kyHCJCmDg+/8dUTJN6fCljvtgCpiki1hBzdIAzlzMTAIUIW5FtJKG5VKfSL686c8a9mqMpwmrLs2uMF691Bxotbvf5t/DF4WjMXUwQg/GNmxrm7nbAS3M3htzVWt8pGehBWZkiO+i9Sn7trMfsdwkG7MlwDJlAqrkuWbQirC2YGlRMHbjV9P84Gc6oltJjg43jRWFM5mZO5x+MvmpWCNmVgYVw3dLszFq+vTATjIvVbl9bZgG/3S7KTPy4x8lzjs0XMIeeH73kf+0/KNh7r/xQbJJCYqboHi9fXXclVDKkP52KnHUwKjr4A==,iv:Z+WK97wRVtSsutlL0ASXi6/bmZ5tSTFnmmEb+elaL6I=,tag:F9jIRwozXXofZB89SuuOXw==,type:str]
    identity_public: ENC[AES256_GCM,data:hWW//4IXWw3/qpOVP/g1k4aG2yBOEdL00DQD+scNAgeUhlKBZkdaPEp9WqBz4OOBjwlHeRjyJM4RFcEafD8WBQeFPQpZ98/ZjRdbLJozBI341zbb5EMljtSTtiY+f3NwSYsFSaGQUHhTynOjpy9/sp7u6/X37EVKJ8Vq+srh/jAywFykZ4L8XMll0T60zGOv6FA2GIpGw6GWLrnCsmTZMm2ftoCslWs0wi0LejTujrABhkkWn5nOb2Wwujvj1VvNwbXI/mkFIdxK0b+MrDKSLVZhwQgrtLfNpMphpDaUFXSJfT2t5UJYjuIzETKmG4QvX3J9VO6xIGfrlOi/lu4RneiZlrc5QAI+j89f/O/hUg==,iv:gYPDC0HAF3gMpzcWC+PJ94cjVa9nUvGXoTR47Ol0ZzY=,tag:c8VQ22MwqM+xEWbkMs5PKA==,type:str]
    #ENC[AES256_GCM,data:eYfmLDXKK/yswcop2tNMOXBcZI3Mu7kXmz6SFaM0knbuia61KhmsChsT5h406hLX0k6i34lKTaiPLBipR6iYoi3a6dPz6Wt4g6Pg08nkmhXEvWQMzS7EU9BvcreXGEIuEbt+,iv:E8pdKPyDzv8Fbib9QWPGJjGZf3mYr0yS67J0JttqCyw=,tag:si/wisg0EHCIPHD/DmiHUA==,type:comment]
    known_hosts: ENC[AES256_GCM,data:G7y/qQUOM1c6dg5DbHVRZ6bbpxmoWJBKBQJC12pv/JzMvJlKQlW0TMvod6ujpL7IEeWfAxI3eXswuc4sNBj+aoPJs/aUIGazDL+cm70uINxgWQzk9gBEbTJI9KNnoBpLTjeICKcY8G8p87gA1UCkEc5fRu1Io6nlwD5gTABmckmIHEosEdqdeCJu73AqDFwke3/O3vUNpIFijHGitRb2CfV9hdNggWY3uGUUFxM2vD+OneIjjFahu5USaLIFb45YFH5Tk+h394BizgfNY9PUkMx21iIlJY4Aevp/hGPo9556WGaGYm8ij/lvC1dAZjLg5cvr9FhbfD4zyyqrWStE8K0b7ylSEujxUYsyKbGu1E5le7dyhmHrXhEBJIyPNuN9DifrF3a28vbIIzxKiFcBNaosvLjuVh79yEBKpzcDLnWV5jEXg5lr2mq7u6pfGsOJGd/E10Tz+NMZZDNSLWIjUAgCneDVDDG/QN+ONqBlgyH0QcsZ4pbb6U2Np/VEt3bwEOU4aVhu1tXLTtABKBajcmLXizbnJEQfzPx3d4Q4xyZ8FyGgXZ3iDuA9Qxs3iINdRrcSvCN5sIIJXPRCy1S9KrMoSV7eampY7QGhLA/Zw9czGe2aK9D1jDfYYoctwMO/aNvWKAm/q4zm+tEWaMpzUnXfu7krTVZ/csLI8j2hhZPOOG5VWqnCRtUnGIetrj9Whcw6mqAm1J1xfncg5sNW5fbP2ILIYgHZUef1wr7/dYpWZOKG6Zi+DsoBsz6IPL+sMaph3+32hT1rygMTcA0jRlDDR5SsGQn7wQhYWTTxm4zyUlKFdLmqqwGd3j7XaI5sYchx/6Gc8sHu67Jne2ijCvFVSZ0Q8z509DPS3p5izOHZJySnK3B+IFpwbjBdZ5Un0ystDs2U18NbZWEk0LgBSNuG1tmhtORPUpYOJDilmYAg1LmkAzMmVtO3+iRvPMiOgGpQh4MGTlw/xfWjw6bhzimopGy4naSNnVdkOCtPb9Lm2vrfvnTBSIyKHPQPNtCZH/0eifA97ksm4KDr3Zz0USYBWViM8aIUBCCoskTmY8MFY19RlcGZ17JDts08rPSz6dL4MiLtdw52Q/Z7,iv:rtmRO250r3UAAnxkf7LBtL9F6bXRS1nQTGxad8jAUuw=,tag:gLfROrn8BfB8DM0yXQfl4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g3tlvcegfpl0nnaufvw57f9q5hl4h5zyuwrvwnwuahe9dauej3rsf0rf9g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z1BnbitHUHRYb2E5TnAx
            SVhXTVVKNm1ibVVhNjlZSVMrQjl3aVpQZWd3CjBWZlNwQ3JoR3pmaVpwVjdYMklU
            UGIzVERLSmlKMGdRMFZEd3RocG9TVkEKLS0tIGR6MlpaQjl0MEMxZ084U2Z0SHFj
            Z3dvWnBBMkNyNUw0ZGc0OGhLYzZrSGcKkzIM+kRVSr/7WIwd+LRjkNRM5KKc+t2U
            Y8fExwbsH5GBW+8SJctnrZCn8qW16VzJnjAfxsDfC1TDntLSAXYxSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-23T22:24:20Z"
    mac: ENC[AES256_GCM,data:ZdRtb0itfxtRHqjk3mriL8njkZQTbVaVL47AP7y+EKdFwdbHGEGG3L0/Il+Ze0BapZZWYepdDzP2yjqsfiK7hrKbwedKe55lsU8Vs5aL/khJSP9zmUxX2QJaezAHqP1BzW8qr6dcbwgWBJ0hoTEKEI0gt7i/PNYIgVyxHvW2vvU=,iv:VNfHI+lHPVCnIZWt3iUdF6cgGTbT1QDBClaCjsI24QY=,tag:bN7dhPw2LytaGDPpwuzZww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
